GET http://localhost:3000/list?path=

###
POST http://localhost:3000/download
Content-Type: application/json

{
    "path": "/WebSite/index.html" 
}

###
POST http://localhost:3000/newDir
Content-Type: application/json

{
    "path": "NEW"
}